name: Post Release Note to Discord

on:
  release:
    types: [published]

jobs:
  discord_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Note to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          RELEASE_NAME=$(echo '${{ github.event.release.name }}' | jq -Rsa .)
          RELEASE_BODY=$(echo '${{ github.event.release.body }}' | jq -Rsa .)
          RELEASE_URL="${{ github.event.release.html_url }}"

          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub Releases",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [{
              "title": '"${RELEASE_NAME}"',
              "description": '"${RELEASE_BODY}"',
              "url": "'"$RELEASE_URL"'",
              "color": 16711680
            }]
          }' "${DISCORD_WEBHOOK}"
