name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Note to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          RELEASE_NAME="${{ github.event.release.name }}"
          RELEASE_BODY=$(echo "${{ github.event.release.body }}" | jq -Rsa .)

          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub Releases",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [{
              "title": "🚀 New Release: '"$RELEASE_NAME"'",
              "description": '"$RELEASE_BODY"'',
              "url": "'"${{ github.event.release.html_url }}"'",
              "color": 16776960
            }]
          }' $DISCORD_WEBHOOK
