name: Test Discord Webhook

on:
  workflow_dispatch:  # ทำให้สามารถกด "Run workflow" ได้เอง

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Test Message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub Actions",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [{
              "title": "✅ Test Message from GitHub Actions",
              "description": "ถ้าคุณเห็นข้อความนี้ แสดงว่า Webhook ทำงานได้ปกติ!",
              "color": 65280
            }]
          }' $DISCORD_WEBHOOK
